version: '2.1'

networks:
  db_network:
    external:
      name: dnet1

services:
  db:
    image: postgres:10.12-alpine
    restart: always
    environment:
      POSTGRES_USER: marine
      POSTGRES_PASSWORD: marine
      POSTGRES_DB: marine
    networks:
      - db_network